version: '3.8'

services:
  client:
    container_name: music-client
    build: ./client
    ports:
      - '80:80'
  backend:
    container_name: music-backend
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}



