version: '3.8'

services:
  client:
    container_name: music-client
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - '80:80'
  backend:
    container_name: music-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - '5000:5000'



